<?php

namespace Modules\Utilities\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Utilities\Entities\Module;

class ModulesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $modules = [
            [
                'module_key' => 'crm',
                'name' => 'CRM',
                'description' => 'Customer Relationship Management',
                'route' => '/dashboard/modules/crm',
                'icon' => 'crm.png',
                'slogan' => 'One call, one deal',
                'navigation' => [
                    ['key' => 'dashboard', 'label' => 'Dashboard', 'route' => '/dashboard/modules/crm', 'icon' => 'LayoutDashboard', 'section' => 'Main'],
                    ['key' => 'companies', 'label' => 'Companies', 'route' => '/dashboard/modules/crm/companies', 'icon' => 'Building2', 'section' => 'Contacts & Accounts'],
                    ['key' => 'contacts', 'label' => 'Contacts', 'route' => '/dashboard/modules/crm/contacts', 'icon' => 'Users', 'section' => 'Contacts & Accounts'],
                    ['key' => 'leads', 'label' => 'Leads', 'route' => '/dashboard/modules/crm/leads', 'icon' => 'Target', 'section' => 'Sales'],
                    ['key' => 'opportunities', 'label' => 'Opportunities', 'route' => '/dashboard/modules/crm/opportunities', 'icon' => 'TrendingUp', 'section' => 'Sales'],
                    ['key' => 'deals', 'label' => 'Deals', 'route' => '/dashboard/modules/crm/deals', 'icon' => 'Handshake', 'section' => 'Sales'],
                    ['key' => 'activities', 'label' => 'Activities', 'route' => '/dashboard/modules/crm/activities', 'icon' => 'CalendarClock', 'section' => 'Sales'],
                    ['key' => 'notes', 'label' => 'Notes', 'route' => '/dashboard/modules/crm/notes', 'icon' => 'StickyNote', 'section' => 'Data'],
                    ['key' => 'files', 'label' => 'Files', 'route' => '/dashboard/modules/crm/files', 'icon' => 'FileText', 'section' => 'Data'],
                    ['key' => 'pipeline-stages', 'label' => 'Pipeline Stages', 'route' => '/dashboard/modules/crm/pipeline-stages', 'icon' => 'GitBranch', 'section' => 'Settings'],
                    ['key' => 'automation', 'label' => 'Automation', 'route' => '/dashboard/modules/crm/automation', 'icon' => 'Zap', 'section' => 'Settings'],
                    ['key' => 'webhooks', 'label' => 'Webhooks', 'route' => '/dashboard/modules/crm/webhooks', 'icon' => 'Webhook', 'section' => 'Settings'],
                    ['key' => 'import', 'label' => 'Import', 'route' => '/dashboard/modules/crm/import', 'icon' => 'Upload', 'section' => 'Settings'],
                    ['key' => 'pipeline', 'label' => 'Pipeline', 'route' => '/dashboard/modules/crm/pipeline', 'icon' => 'Columns3', 'section' => 'Sales'],
                ],
                'theme' => [
                    'primary_color' => '#3B82F6',
                    'secondary_color' => '#1E40AF',
                ],
                'status' => 'active',
            ],
            [
                'module_key' => 'survey',
                'name' => 'Survey',
                'description' => 'Create surveys, collect responses, and analyze results with advanced branching logic and real-time analytics',
                'route' => '/dashboard/modules/survey/',
                'icon' => 'FileText',
                'slogan' => 'Collect insights that drive decisions',
                'navigation' => [
                    ['key' => 'dashboard', 'label' => 'Dashboard', 'route' => '/dashboard/modules/survey', 'icon' => 'LayoutDashboard', 'section' => 'Main'],
                    ['key' => 'surveys', 'label' => 'Surveys', 'route' => '/dashboard/modules/survey/surveys', 'icon' => 'FileText', 'section' => 'Management'],
                    ['key' => 'templates', 'label' => 'Templates', 'route' => '/dashboard/modules/survey/templates', 'icon' => 'Copy', 'section' => 'Management'],
                    ['key' => 'themes', 'label' => 'Themes', 'route' => '/dashboard/modules/survey/themes', 'icon' => 'Palette', 'section' => 'Management'],
                    ['key' => 'responses', 'label' => 'Responses', 'route' => '/dashboard/modules/survey/responses', 'icon' => 'MessageSquare', 'section' => 'Data & Insights'],
                    ['key' => 'analytics', 'label' => 'Analytics', 'route' => '/dashboard/modules/survey/analytics', 'icon' => 'BarChart3', 'section' => 'Data & Insights'],
                    ['key' => 'automation', 'label' => 'Automation', 'route' => '/dashboard/modules/survey/automation', 'icon' => 'Zap', 'section' => 'Integrations'],
                    ['key' => 'webhooks', 'label' => 'Webhooks', 'route' => '/dashboard/modules/survey/webhooks', 'icon' => 'Webhook', 'section' => 'Integrations'],
                ],
                'theme' => [
                    'primary_color' => '#8B5CF6',
                    'secondary_color' => '#5B21B6',
                ],
                'status' => 'active',
            ],
            [
                'module_key' => 'pos',
                'name' => 'POS',
                'description' => 'Point of Sale',
                'route' => '/dashboard/modules/pos',
                'icon' => 'pos.png',
                'slogan' => 'Sales made easy',
                'navigation' => [
                    ['key' => 'dashboard', 'label' => 'Dashboard', 'route' => '/dashboard/modules/pos', 'icon' => 'LayoutDashboard', 'section' => 'Main'],
                    ['key' => 'products', 'label' => 'Products', 'route' => '/dashboard/modules/pos/products', 'icon' => 'Package', 'section' => 'Catalog'],
                    ['key' => 'categories', 'label' => 'Categories', 'route' => '/dashboard/modules/pos/categories', 'icon' => 'Folder', 'section' => 'Catalog'],
                    ['key' => 'sub-categories', 'label' => 'Sub-Categories', 'route' => '/dashboard/modules/pos/sub-categories', 'icon' => 'Folders', 'section' => 'Catalog'],
                    ['key' => 'tags', 'label' => 'Tags', 'route' => '/dashboard/modules/pos/tags', 'icon' => 'Tags', 'section' => 'Catalog'],
                    ['key' => 'barcodes', 'label' => 'Barcodes', 'route' => '/dashboard/modules/pos/barcodes', 'icon' => 'Barcode', 'section' => 'Catalog'],
                    ['key' => 'offer-prices', 'label' => 'Offer Prices', 'route' => '/dashboard/modules/pos/offer-prices', 'icon' => 'Tag', 'section' => 'Pricing'],
                    ['key' => 'damaged', 'label' => 'Damaged', 'route' => '/dashboard/modules/pos/damaged', 'icon' => 'AlertTriangle', 'section' => 'Inventory'],
                    ['key' => 'orders', 'label' => 'Orders', 'route' => '/dashboard/modules/pos/orders', 'icon' => 'Receipt', 'section' => 'Sales'],
                ],
                'theme' => [
                    'primary_color' => '#10B981',
                    'secondary_color' => '#047857',
                ],
                'status' => 'active',
            ],
            [
                'module_key' => 'hr',
                'name' => 'HR',
                'description' => 'Human Resources',
                'route' => '/dashboard/modules/hr',
                'icon' => 'hr.png',
                'slogan' => 'Managing human resources',
                'navigation' => [
                    ['key' => 'dashboard', 'label' => 'Dashboard', 'route' => '/dashboard/modules/hr', 'icon' => 'LayoutDashboard', 'section' => 'Main'],
                    ['key' => 'departments', 'label' => 'Departments', 'route' => '/dashboard/modules/hr/departments', 'icon' => 'Building2', 'section' => 'Organization'],
                    ['key' => 'employees', 'label' => 'Employees', 'route' => '/dashboard/modules/hr/employees', 'icon' => 'Users', 'section' => 'Organization'],
                    ['key' => 'positions', 'label' => 'Positions', 'route' => '/dashboard/modules/hr/positions', 'icon' => 'Briefcase', 'section' => 'Organization'],
                    ['key' => 'shifts', 'label' => 'Shifts', 'route' => '/dashboard/modules/hr/shifts', 'icon' => 'Clock3', 'section' => 'Organization'],
                    ['key' => 'leave_types', 'label' => 'Leave Types', 'route' => '/dashboard/modules/hr/leave-types', 'icon' => 'CalendarRange', 'section' => 'Time & Attendance'],
                    ['key' => 'leave_requests', 'label' => 'Leave Requests', 'route' => '/dashboard/modules/hr/leave-requests', 'icon' => 'FileText', 'section' => 'Time & Attendance'],
                    ['key' => 'holidays', 'label' => 'Holidays', 'route' => '/dashboard/modules/hr/holidays', 'icon' => 'CalendarDays', 'section' => 'Time & Attendance'],
                    ['key' => 'payrolls', 'label' => 'Payroll', 'route' => '/dashboard/modules/hr/payrolls', 'icon' => 'Wallet', 'section' => 'Payroll & Performance'],
                    ['key' => 'performance_cycles', 'label' => 'Performance', 'route' => '/dashboard/modules/hr/performance-cycles', 'icon' => 'LineChart', 'section' => 'Payroll & Performance'],
                    ['key' => 'recruitment', 'label' => 'Recruitment', 'route' => '/dashboard/modules/hr/recruitment', 'icon' => 'Briefcase', 'section' => 'Recruitment'],
                    ['key' => 'candidates', 'label' => 'Candidates', 'route' => '/dashboard/modules/hr/candidates', 'icon' => 'UsersRound', 'section' => 'Recruitment'],
                    ['key' => 'applications', 'label' => 'Applications', 'route' => '/dashboard/modules/hr/applications', 'icon' => 'KanbanSquare', 'section' => 'Recruitment'],
                    ['key' => 'interviews', 'label' => 'Interviews', 'route' => '/dashboard/modules/hr/interviews', 'icon' => 'CalendarClock', 'section' => 'Recruitment'],
                    ['key' => 'offers', 'label' => 'Offers', 'route' => '/dashboard/modules/hr/offers', 'icon' => 'BadgeDollarSign', 'section' => 'Recruitment'],
                    ['key' => 'onboarding', 'label' => 'Onboarding', 'route' => '/dashboard/modules/hr/onboarding', 'icon' => 'ClipboardCheck', 'section' => 'Recruitment'],
                    ['key' => 'training', 'label' => 'Training', 'route' => '/dashboard/modules/hr/training', 'icon' => 'GraduationCap', 'section' => 'Development'],
                    ['key' => 'assets', 'label' => 'Assets', 'route' => '/dashboard/modules/hr/assets', 'icon' => 'Package', 'section' => 'Assets & Finance'],
                    ['key' => 'expenses', 'label' => 'Expenses', 'route' => '/dashboard/modules/hr/expenses', 'icon' => 'Receipt', 'section' => 'Assets & Finance'],
                    ['key' => 'announcements', 'label' => 'Announcements', 'route' => '/dashboard/modules/hr/announcements', 'icon' => 'Megaphone', 'section' => 'Others'],
                    ['key' => 'reports', 'label' => 'Reports', 'route' => '/dashboard/modules/hr/reports', 'icon' => 'BarChart3', 'section' => 'Others'],
                    ['key' => 'self-service', 'label' => 'Self-Service', 'route' => '/dashboard/modules/hr/me', 'icon' => 'UserCog', 'section' => 'Others'],
                ],
                'theme' => [
                    'primary_color' => '#F59E0B',
                    'secondary_color' => '#B45309',
                ],
                'status' => 'active',
            ],
            [
                'module_key' => 'events',
                'name' => 'events',
                'description' => 'Events is a good module',
                'route' => '/events/',
                'icon' => 'events.png',
                'slogan' => 'Create and manage events',
                'theme' => [
                    'primary_color' => '#EC4899',
                    'secondary_color' => '#9D174D',
                ],
                'status' => 'inactive',
            ],
            [
                'module_key' => 'cms',
                'name' => 'cms',
                'description' => 'CMS is a good module',
                'route' => '/cms/',
                'icon' => 'cms.png',
                'slogan' => 'Manage your content',
                'theme' => [
                    'primary_color' => '#6366F1',
                    'secondary_color' => '#4338CA',
                ],
                'status' => 'inactive',
            ],
            [
                'module_key' => 'sms_marketing',
                'name' => 'SMS Marketing',
                'description' => 'SMS campaign management with scheduling, templates, contact lists, A/B testing, automation, and analytics',
                'route' => '/dashboard/modules/sms-marketing',
                'icon' => 'Smartphone',
                'slogan' => 'Reach customers directly',
                'navigation' => [
                    ['key' => 'dashboard', 'label' => 'Dashboard', 'route' => '/dashboard/modules/sms-marketing', 'icon' => 'LayoutDashboard', 'section' => 'Main'],
                    ['key' => 'campaigns', 'label' => 'Campaigns', 'route' => '/dashboard/modules/sms-marketing/campaigns', 'icon' => 'Megaphone', 'section' => 'Campaigns'],
                    ['key' => 'templates', 'label' => 'Templates', 'route' => '/dashboard/modules/sms-marketing/templates', 'icon' => 'FileText', 'section' => 'Campaigns'],
                    ['key' => 'ab-tests', 'label' => 'A/B Tests', 'route' => '/dashboard/modules/sms-marketing/ab-tests', 'icon' => 'Split', 'section' => 'Campaigns'],
                    ['key' => 'contact-lists', 'label' => 'Contact Lists', 'route' => '/dashboard/modules/sms-marketing/contact-lists', 'icon' => 'Users', 'section' => 'Audience'],
                    ['key' => 'contacts', 'label' => 'Contacts', 'route' => '/dashboard/modules/sms-marketing/contacts', 'icon' => 'Contact', 'section' => 'Audience'],
                    ['key' => 'sending-logs', 'label' => 'Sending Logs', 'route' => '/dashboard/modules/sms-marketing/sending-logs', 'icon' => 'List', 'section' => 'Data & Insights'],
                    ['key' => 'analytics', 'label' => 'Analytics', 'route' => '/dashboard/modules/sms-marketing/analytics', 'icon' => 'BarChart3', 'section' => 'Data & Insights'],
                    ['key' => 'import', 'label' => 'Import', 'route' => '/dashboard/modules/sms-marketing/import', 'icon' => 'Upload', 'section' => 'Data & Insights'],
                    ['key' => 'automation', 'label' => 'Automation', 'route' => '/dashboard/modules/sms-marketing/automation', 'icon' => 'Zap', 'section' => 'Settings'],
                    ['key' => 'webhooks', 'label' => 'Webhooks', 'route' => '/dashboard/modules/sms-marketing/webhooks', 'icon' => 'Webhook', 'section' => 'Settings'],
                    ['key' => 'credentials', 'label' => 'Credentials', 'route' => '/dashboard/modules/sms-marketing/credentials', 'icon' => 'Key', 'section' => 'Settings'],
                ],
                'theme' => [
                    'primary_color' => '#EF4444',
                    'secondary_color' => '#B91C1C',
                ],
                'status' => 'active',
            ],
            [
                'module_key' => 'email_marketing',
                'name' => 'Email Marketing',
                'description' => 'Email campaign management with scheduling, templates, contact lists, A/B testing, automation, and analytics',
                'route' => '/dashboard/modules/email-marketing',
                'icon' => 'Mail',
                'slogan' => 'Engage through emails',
                'navigation' => [
                    ['key' => 'dashboard', 'label' => 'Dashboard', 'route' => '/dashboard/modules/email-marketing', 'icon' => 'LayoutDashboard', 'section' => 'Main'],
                    ['key' => 'campaigns', 'label' => 'Campaigns', 'route' => '/dashboard/modules/email-marketing/campaigns', 'icon' => 'Megaphone', 'section' => 'Campaigns'],
                    ['key' => 'templates', 'label' => 'Templates', 'route' => '/dashboard/modules/email-marketing/templates', 'icon' => 'FileText', 'section' => 'Campaigns'],
                    ['key' => 'ab-tests', 'label' => 'A/B Tests', 'route' => '/dashboard/modules/email-marketing/ab-tests', 'icon' => 'Split', 'section' => 'Campaigns'],
                    ['key' => 'contact-lists', 'label' => 'Contact Lists', 'route' => '/dashboard/modules/email-marketing/contact-lists', 'icon' => 'Users', 'section' => 'Audience'],
                    ['key' => 'contacts', 'label' => 'Contacts', 'route' => '/dashboard/modules/email-marketing/contacts', 'icon' => 'Contact', 'section' => 'Audience'],
                    ['key' => 'sending-logs', 'label' => 'Sending Logs', 'route' => '/dashboard/modules/email-marketing/sending-logs', 'icon' => 'List', 'section' => 'Data & Insights'],
                    ['key' => 'analytics', 'label' => 'Analytics', 'route' => '/dashboard/modules/email-marketing/analytics', 'icon' => 'BarChart3', 'section' => 'Data & Insights'],
                    ['key' => 'import', 'label' => 'Import', 'route' => '/dashboard/modules/email-marketing/import', 'icon' => 'Upload', 'section' => 'Data & Insights'],
                    ['key' => 'automation', 'label' => 'Automation', 'route' => '/dashboard/modules/email-marketing/automation', 'icon' => 'Zap', 'section' => 'Settings'],
                    ['key' => 'webhooks', 'label' => 'Webhooks', 'route' => '/dashboard/modules/email-marketing/webhooks', 'icon' => 'Webhook', 'section' => 'Settings'],
                    ['key' => 'credentials', 'label' => 'Credentials', 'route' => '/dashboard/modules/email-marketing/credentials', 'icon' => 'Key', 'section' => 'Settings'],
                ],
                'theme' => [
                    'primary_color' => '#14B8A6',
                    'secondary_color' => '#0F766E',
                ],
                'status' => 'active',
            ],
            [
                'module_key' => 'social_media_marketing',
                'name' => 'social media marketing',
                'description' => 'Social Media Marketing is a good module',
                'route' => '/social-media-marketing/',
                'icon' => 'social_media_marketing.png',
                'slogan' => 'Grow your presence online',
                'theme' => [
                    'primary_color' => '#3B82F6',
                    'secondary_color' => '#1D4ED8',
                ],
                'status' => 'inactive',
            ],
            [
                'module_key' => 'e_commerce',
                'name' => 'e-commerce',
                'description' => 'E-commerce is a good module',
                'route' => '/e-commerce/',
                'icon' => 'e_commerce.png',
                'slogan' => 'Sell your products online',
                'theme' => [
                    'primary_color' => '#F97316',
                    'secondary_color' => '#C2410C',
                ],
                'status' => 'inactive',
            ],
            [
                'module_key' => 'live_agent',
                'name' => 'live agent',
                'description' => 'Live Agent is a good module',
                'route' => '/live-agent/',
                'icon' => 'live_agent.png',
                'slogan' => 'Live customer support',
                'theme' => [
                    'primary_color' => '#06B6D4',
                    'secondary_color' => '#0E7490',
                ],
                'status' => 'inactive',
            ],
            [
                'module_key' => 'expenses',
                'name' => 'Expenses',
                'description' => 'Expense management with approval workflows, reimbursements, policy validation, and receipt tracking',
                'route' => '/dashboard/modules/expenses',
                'icon' => 'Receipt',
                'slogan' => 'Spend smart, reimburse fast',
                'navigation' => [
                    ['key' => 'dashboard', 'label' => 'Dashboard', 'route' => '/dashboard/modules/expenses', 'icon' => 'LayoutDashboard', 'section' => 'Main'],
                    ['key' => 'expenses', 'label' => 'Expenses', 'route' => '/dashboard/modules/expenses/expenses', 'icon' => 'Receipt', 'section' => 'Management'],
                    ['key' => 'categories', 'label' => 'Categories', 'route' => '/dashboard/modules/expenses/categories', 'icon' => 'Folder', 'section' => 'Management'],
                    ['key' => 'reports', 'label' => 'Expense Reports', 'route' => '/dashboard/modules/expenses/reports', 'icon' => 'FileText', 'section' => 'Management'],
                    ['key' => 'reimbursements', 'label' => 'Reimbursements', 'route' => '/dashboard/modules/expenses/reimbursements', 'icon' => 'Wallet', 'section' => 'Finance'],
                    ['key' => 'policies', 'label' => 'Policies', 'route' => '/dashboard/modules/expenses/policies', 'icon' => 'Shield', 'section' => 'Settings'],
                    ['key' => 'tags', 'label' => 'Tags', 'route' => '/dashboard/modules/expenses/tags', 'icon' => 'Tags', 'section' => 'Settings'],
                ],
                'theme' => [
                    'primary_color' => '#84CC16',
                    'secondary_color' => '#4D7C0F',
                ],
                'status' => 'active',
            ],
            [
                'module_key' => 'inventory',
                'name' => 'Inventory',
                'description' => 'Manage warehouses, stock moves, and inventory tracking',
                'route' => '/dashboard/modules/inventory',
                'icon' => 'Package',
                'slogan' => 'Manage your stock',
                'navigation' => [
                    ['key' => 'dashboard', 'label' => 'Dashboard', 'route' => '/dashboard/modules/inventory', 'icon' => 'LayoutDashboard', 'section' => 'Main'],
                    ['key' => 'warehouses', 'label' => 'Warehouses', 'route' => '/dashboard/modules/inventory/warehouses', 'icon' => 'Warehouse', 'section' => 'Management'],
                    ['key' => 'stock-moves', 'label' => 'Stock Moves', 'route' => '/dashboard/modules/inventory/stock-moves', 'icon' => 'ArrowLeftRight', 'section' => 'Management'],
                ],
                'theme' => [
                    'primary_color' => '#A855F7',
                    'secondary_color' => '#7E22CE',
                ],
                'status' => 'active',
            ],
            [
                'module_key' => 'accounting',
                'name' => 'Accounting',
                'description' => 'Double-entry bookkeeping, chart of accounts, journal entries, budgets, tax rates, bank reconciliation, and financial reporting',
                'route' => '/dashboard/modules/accounting',
                'icon' => 'Landmark',
                'slogan' => 'Your books, balanced',
                'navigation' => [
                    ['key' => 'dashboard', 'label' => 'Dashboard', 'route' => '/dashboard/modules/accounting', 'icon' => 'LayoutDashboard', 'section' => 'Main'],
                    ['key' => 'chart-of-accounts', 'label' => 'Chart of Accounts', 'route' => '/dashboard/modules/accounting/chart-of-accounts', 'icon' => 'BookOpen', 'section' => 'Core'],
                    ['key' => 'journal-entries', 'label' => 'Journal Entries', 'route' => '/dashboard/modules/accounting/journal-entries', 'icon' => 'FileText', 'section' => 'Core'],
                    ['key' => 'fiscal-years', 'label' => 'Fiscal Years', 'route' => '/dashboard/modules/accounting/fiscal-years', 'icon' => 'Calendar', 'section' => 'Core'],
                    ['key' => 'budgets', 'label' => 'Budgets', 'route' => '/dashboard/modules/accounting/budgets', 'icon' => 'PiggyBank', 'section' => 'Planning'],
                    ['key' => 'tax-rates', 'label' => 'Tax Rates', 'route' => '/dashboard/modules/accounting/tax-rates', 'icon' => 'Percent', 'section' => 'Planning'],
                    ['key' => 'bank-accounts', 'label' => 'Bank Accounts', 'route' => '/dashboard/modules/accounting/bank-accounts', 'icon' => 'Landmark', 'section' => 'Banking'],
                    ['key' => 'bank-transactions', 'label' => 'Bank Transactions', 'route' => '/dashboard/modules/accounting/bank-transactions', 'icon' => 'ArrowLeftRight', 'section' => 'Banking'],
                    ['key' => 'reconciliation', 'label' => 'Reconciliation', 'route' => '/dashboard/modules/accounting/reconciliation', 'icon' => 'CheckCircle', 'section' => 'Banking'],
                    ['key' => 'reports', 'label' => 'Reports', 'route' => '/dashboard/modules/accounting/reports', 'icon' => 'BarChart3', 'section' => 'Insights'],
                ],
                'theme' => [
                    'primary_color' => '#22C55E',
                    'secondary_color' => '#15803D',
                ],
                'status' => 'active',
            ],
            [
                'module_key' => 'e_learning',
                'name' => 'e-learning',
                'description' => 'E-learning is a good module',
                'route' => '/e-learning/',
                'icon' => 'e_learning.png',
                'slogan' => 'Learn and grow',
                'theme' => [
                    'primary_color' => '#EAB308',
                    'secondary_color' => '#A16207',
                ],
                'status' => 'inactive',
            ],
            [
                'module_key' => 'sales',
                'name' => 'Sales',
                'description' => 'Manage sales orders, track fulfillment, and process cancellations',
                'route' => '/dashboard/modules/sales',
                'icon' => 'Receipt',
                'slogan' => 'Close the deal',
                'navigation' => [
                    ['key' => 'dashboard', 'label' => 'Dashboard', 'route' => '/dashboard/modules/sales', 'icon' => 'LayoutDashboard', 'section' => 'Main'],
                    ['key' => 'orders', 'label' => 'Orders', 'route' => '/dashboard/modules/sales/orders', 'icon' => 'Receipt', 'section' => 'Orders'],
                ],
                'theme' => [
                    'primary_color' => '#F97316',
                    'secondary_color' => '#C2410C',
                ],
                'status' => 'active',
            ],
            [
                'module_key' => 'project_management',
                'name' => 'Project Management',
                'description' => 'Plan, track, and deliver projects with Kanban boards, timelines, dependencies, risks, and templates',
                'route' => '/dashboard/modules/project-management',
                'icon' => 'FolderKanban',
                'slogan' => 'Deliver with clarity',
                'navigation' => [
                    ['key' => 'dashboard', 'label' => 'Dashboard', 'route' => '/dashboard/modules/project-management', 'icon' => 'LayoutDashboard', 'section' => 'Main'],
                    ['key' => 'projects', 'label' => 'Projects', 'route' => '/dashboard/modules/project-management/projects', 'icon' => 'Folder', 'section' => 'Delivery'],
                    ['key' => 'board', 'label' => 'Board', 'route' => '/dashboard/modules/project-management/board', 'icon' => 'KanbanSquare', 'section' => 'Delivery'],
                    ['key' => 'tasks', 'label' => 'Tasks', 'route' => '/dashboard/modules/project-management/tasks', 'icon' => 'CheckSquare', 'section' => 'Delivery'],
                    ['key' => 'timeline', 'label' => 'Timeline', 'route' => '/dashboard/modules/project-management/timeline', 'icon' => 'GanttChart', 'section' => 'Delivery'],
                    ['key' => 'milestones', 'label' => 'Milestones', 'route' => '/dashboard/modules/project-management/milestones', 'icon' => 'Flag', 'section' => 'Delivery'],
                    ['key' => 'risks', 'label' => 'Risks', 'route' => '/dashboard/modules/project-management/risks', 'icon' => 'AlertTriangle', 'section' => 'Governance'],
                    ['key' => 'issues', 'label' => 'Issues', 'route' => '/dashboard/modules/project-management/issues', 'icon' => 'Bug', 'section' => 'Governance'],
                    ['key' => 'templates', 'label' => 'Templates', 'route' => '/dashboard/modules/project-management/templates', 'icon' => 'Copy', 'section' => 'Governance'],
                    ['key' => 'reports', 'label' => 'Reports', 'route' => '/dashboard/modules/project-management/reports', 'icon' => 'BarChart3', 'section' => 'Insights'],
                    ['key' => 'automation', 'label' => 'Automation', 'route' => '/dashboard/modules/project-management/automation', 'icon' => 'Zap', 'section' => 'Integrations'],
                    ['key' => 'webhooks', 'label' => 'Webhooks', 'route' => '/dashboard/modules/project-management/webhooks', 'icon' => 'Webhook', 'section' => 'Integrations'],
                ],
                'theme' => [
                    'primary_color' => '#2563EB',
                    'secondary_color' => '#1E3A8A',
                ],
                'status' => 'active',
            ],
            [
                'module_key' => 'time_management',
                'name' => 'Time Management',
                'description' => 'Track time, manage calendars with Google/Outlook sync, generate meeting links, and monitor productivity',
                'route' => '/dashboard/modules/time-management',
                'icon' => 'Clock',
                'slogan' => 'Master your time',
                'navigation' => [
                    ['key' => 'dashboard', 'label' => 'Dashboard', 'route' => '/dashboard/modules/time-management', 'icon' => 'LayoutDashboard', 'section' => 'Main'],
                    ['key' => 'calendar', 'label' => 'Calendar', 'route' => '/dashboard/modules/time-management/calendar', 'icon' => 'Calendar', 'section' => 'Main'],
                    ['key' => 'timer', 'label' => 'My Timer', 'route' => '/dashboard/modules/time-management/timer', 'icon' => 'Timer', 'section' => 'Tracking'],
                    ['key' => 'time-entries', 'label' => 'Time Entries', 'route' => '/dashboard/modules/time-management/time-entries', 'icon' => 'Clock', 'section' => 'Tracking'],
                    ['key' => 'timesheets', 'label' => 'Timesheets', 'route' => '/dashboard/modules/time-management/timesheets', 'icon' => 'FileText', 'section' => 'Tracking'],
                    ['key' => 'attendance', 'label' => 'Attendance', 'route' => '/dashboard/modules/time-management/attendance', 'icon' => 'UserCheck', 'section' => 'Workforce'],
                    ['key' => 'schedules', 'label' => 'Schedules', 'route' => '/dashboard/modules/time-management/schedules', 'icon' => 'CalendarDays', 'section' => 'Workforce'],
                    ['key' => 'overtime', 'label' => 'Overtime', 'route' => '/dashboard/modules/time-management/overtime', 'icon' => 'ClockAlert', 'section' => 'Workforce'],
                    ['key' => 'meeting-links', 'label' => 'Meeting Links', 'route' => '/dashboard/modules/time-management/meeting-links', 'icon' => 'Video', 'section' => 'Meetings'],
                    ['key' => 'calendar-sync', 'label' => 'Calendar Sync', 'route' => '/dashboard/modules/time-management/calendar-sync', 'icon' => 'RefreshCw', 'section' => 'Meetings'],
                    ['key' => 'reports', 'label' => 'Reports', 'route' => '/dashboard/modules/time-management/reports', 'icon' => 'BarChart3', 'section' => 'Insights'],
                    ['key' => 'policies', 'label' => 'Policies', 'route' => '/dashboard/modules/time-management/policies', 'icon' => 'Shield', 'section' => 'Settings'],
                    ['key' => 'automation', 'label' => 'Automation', 'route' => '/dashboard/modules/time-management/automation', 'icon' => 'Zap', 'section' => 'Settings'],
                    ['key' => 'webhooks', 'label' => 'Webhooks', 'route' => '/dashboard/modules/time-management/webhooks', 'icon' => 'Webhook', 'section' => 'Settings'],
                ],
                'theme' => [
                    'primary_color' => '#D946EF',
                    'secondary_color' => '#A21CAF',
                ],
                'status' => 'active',
            ],
        ];

        foreach ($modules as $module) {
            $existingModule = Module::where('module_key', $module['module_key'])->first();
            if ($existingModule) {
                $existingModule->update($module);
            } else {
                Module::create($module);
            }
        }
    }
}
