<?php

namespace Modules\Utilities\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Utilities\Entities\Currency;
use Carbon\Carbon;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $currencies = [
            [
                'code' => 'USD',
                'name' => 'US Dollar',
                'symbol' => '$',
                'decimal_places' => 2,
                'exchange_rate' => 1.000000,
                'exchange_rate_last_updated' => Carbon::now(),
                'symbol_position' => 'left',
                'base_currency' => true,
                'priority' => 1,
                'note' => 'Base currency for the system',
                'status' => true,
            ],
            [
                'code' => 'EUR',
                'name' => 'Euro',
                'symbol' => '€',
                'decimal_places' => 2,
                'exchange_rate' => 0.850000,
                'exchange_rate_last_updated' => Carbon::now(),
                'symbol_position' => 'left',
                'base_currency' => false,
                'priority' => 2,
                'note' => 'European Union currency',
                'status' => true,
            ],
            [
                'code' => 'GBP',
                'name' => 'British Pound',
                'symbol' => '£',
                'decimal_places' => 2,
                'exchange_rate' => 0.730000,
                'exchange_rate_last_updated' => Carbon::now(),
                'symbol_position' => 'left',
                'base_currency' => false,
                'priority' => 3,
                'note' => 'United Kingdom currency',
                'status' => true,
            ],
            [
                'code' => 'JPY',
                'name' => 'Japanese Yen',
                'symbol' => '¥',
                'decimal_places' => 0,
                'exchange_rate' => 110.000000,
                'exchange_rate_last_updated' => Carbon::now(),
                'symbol_position' => 'left',
                'base_currency' => false,
                'priority' => 4,
                'note' => 'Japanese currency',
                'status' => true,
            ],
            [
                'code' => 'CAD',
                'name' => 'Canadian Dollar',
                'symbol' => 'C$',
                'decimal_places' => 2,
                'exchange_rate' => 1.250000,
                'exchange_rate_last_updated' => Carbon::now(),
                'symbol_position' => 'left',
                'base_currency' => false,
                'priority' => 5,
                'note' => 'Canadian currency',
                'status' => true,
            ],
            [
                'code' => 'AUD',
                'name' => 'Australian Dollar',
                'symbol' => 'A$',
                'decimal_places' => 2,
                'exchange_rate' => 1.350000,
                'exchange_rate_last_updated' => Carbon::now(),
                'symbol_position' => 'left',
                'base_currency' => false,
                'priority' => 6,
                'note' => 'Australian currency',
                'status' => true,
            ],
            [
                'code' => 'CHF',
                'name' => 'Swiss Franc',
                'symbol' => 'CHF',
                'decimal_places' => 2,
                'exchange_rate' => 0.920000,
                'exchange_rate_last_updated' => Carbon::now(),
                'symbol_position' => 'right',
                'base_currency' => false,
                'priority' => 7,
                'note' => 'Swiss currency',
                'status' => true,
            ],
            [
                'code' => 'CNY',
                'name' => 'Chinese Yuan',
                'symbol' => '¥',
                'decimal_places' => 2,
                'exchange_rate' => 6.450000,
                'exchange_rate_last_updated' => Carbon::now(),
                'symbol_position' => 'left',
                'base_currency' => false,
                'priority' => 8,
                'note' => 'Chinese currency',
                'status' => true,
            ],
            [
                'code' => 'INR',
                'name' => 'Indian Rupee',
                'symbol' => '₹',
                'decimal_places' => 2,
                'exchange_rate' => 74.000000,
                'exchange_rate_last_updated' => Carbon::now(),
                'symbol_position' => 'left',
                'base_currency' => false,
                'priority' => 9,
                'note' => 'Indian currency',
                'status' => true,
            ],
            [
                'code' => 'BRL',
                'name' => 'Brazilian Real',
                'symbol' => 'R$',
                'decimal_places' => 2,
                'exchange_rate' => 5.200000,
                'exchange_rate_last_updated' => Carbon::now(),
                'symbol_position' => 'left',
                'base_currency' => false,
                'priority' => 10,
                'note' => 'Brazilian currency',
                'status' => true,
            ],
            [
                'code' => 'MXN',
                'name' => 'Mexican Peso',
                'symbol' => '$',
                'decimal_places' => 2,
                'exchange_rate' => 20.000000,
                'exchange_rate_last_updated' => Carbon::now(),
                'symbol_position' => 'left',
                'base_currency' => false,
                'priority' => 11,
                'note' => 'Mexican currency',
                'status' => true,
            ],
            [
                'code' => 'KRW',
                'name' => 'South Korean Won',
                'symbol' => '₩',
                'decimal_places' => 0,
                'exchange_rate' => 1180.000000,
                'exchange_rate_last_updated' => Carbon::now(),
                'symbol_position' => 'left',
                'base_currency' => false,
                'priority' => 12,
                'note' => 'South Korean currency',
                'status' => true,
            ],
            [
                'code' => 'SGD',
                'name' => 'Singapore Dollar',
                'symbol' => 'S$',
                'decimal_places' => 2,
                'exchange_rate' => 1.350000,
                'exchange_rate_last_updated' => Carbon::now(),
                'symbol_position' => 'left',
                'base_currency' => false,
                'priority' => 13,
                'note' => 'Singapore currency',
                'status' => true,
            ],
            [
                'code' => 'HKD',
                'name' => 'Hong Kong Dollar',
                'symbol' => 'HK$',
                'decimal_places' => 2,
                'exchange_rate' => 7.800000,
                'exchange_rate_last_updated' => Carbon::now(),
                'symbol_position' => 'left',
                'base_currency' => false,
                'priority' => 14,
                'note' => 'Hong Kong currency',
                'status' => true,
            ],
            [
                'code' => 'NZD',
                'name' => 'New Zealand Dollar',
                'symbol' => 'NZ$',
                'decimal_places' => 2,
                'exchange_rate' => 1.400000,
                'exchange_rate_last_updated' => Carbon::now(),
                'symbol_position' => 'left',
                'base_currency' => false,
                'priority' => 15,
                'note' => 'New Zealand currency',
                'status' => true,
            ],
            [
                'code' => 'SEK',
                'name' => 'Swedish Krona',
                'symbol' => 'kr',
                'decimal_places' => 2,
                'exchange_rate' => 8.500000,
                'exchange_rate_last_updated' => Carbon::now(),
                'symbol_position' => 'right',
                'base_currency' => false,
                'priority' => 16,
                'note' => 'Swedish currency',
                'status' => true,
            ],
            [
                'code' => 'NOK',
                'name' => 'Norwegian Krone',
                'symbol' => 'kr',
                'decimal_places' => 2,
                'exchange_rate' => 8.800000,
                'exchange_rate_last_updated' => Carbon::now(),
                'symbol_position' => 'right',
                'base_currency' => false,
                'priority' => 17,
                'note' => 'Norwegian currency',
                'status' => true,
            ],
            [
                'code' => 'DKK',
                'name' => 'Danish Krone',
                'symbol' => 'kr',
                'decimal_places' => 2,
                'exchange_rate' => 6.300000,
                'exchange_rate_last_updated' => Carbon::now(),
                'symbol_position' => 'right',
                'base_currency' => false,
                'priority' => 18,
                'note' => 'Danish currency',
                'status' => true,
            ],
            [
                'code' => 'PLN',
                'name' => 'Polish Zloty',
                'symbol' => 'zł',
                'decimal_places' => 2,
                'exchange_rate' => 3.900000,
                'exchange_rate_last_updated' => Carbon::now(),
                'symbol_position' => 'right',
                'base_currency' => false,
                'priority' => 19,
                'note' => 'Polish currency',
                'status' => true,
            ],
            [
                'code' => 'CZK',
                'name' => 'Czech Koruna',
                'symbol' => 'Kč',
                'decimal_places' => 2,
                'exchange_rate' => 21.500000,
                'exchange_rate_last_updated' => Carbon::now(),
                'symbol_position' => 'right',
                'base_currency' => false,
                'priority' => 20,
                'note' => 'Czech currency',
                'status' => true,
            ],
        ];

        foreach ($currencies as $currencyData) {
            Currency::create($currencyData);
        }

        $this->command->info('Currencies seeded successfully!');
    }
}
