import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertTriangle,
  ArrowLeftRight,
  BadgeDollarSign,
  BarChart3,
  Barcode,
  BookOpen,
  Briefcase,
  Building2,
  Bug,
  Calendar,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  CheckCircle,
  CheckSquare,
  ClipboardCheck,
  Clock,
  Clock3,
  ClockAlert,
  Columns3,
  Copy,
  Contact,
  FileText,
  Flag,
  Folder,
  FolderKanban,
  Folders,
  GanttChart,
  GitBranch,
  GraduationCap,
  Handshake,
  Headphones,
  KanbanSquare,
  Key,
  Landmark,
  LayoutDashboard,
  LineChart,
  List,
  Lock,
  Mail,
  Megaphone,
  MessageSquare,
  Package,
  Palette,
  Percent,
  PiggyBank,
  Receipt,
  RefreshCw,
  Settings2,
  Share2,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Split,
  StickyNote,
  Tag,
  Tags,
  Target,
  Ticket,
  Timer,
  TrendingUp,
  Upload,
  User,
  UserCheck,
  UserCog,
  Users,
  UsersRound,
  Video,
  Wallet,
  Warehouse,
  Webhook,
  Zap,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  Activity,
  AlertTriangle,
  ArrowLeftRight,
  BadgeDollarSign,
  BarChart3,
  Barcode,
  BookOpen,
  Briefcase,
  Building2,
  Bug,
  Calendar,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  CheckCircle,
  CheckSquare,
  ClipboardCheck,
  Clock,
  Clock3,
  ClockAlert,
  Columns3,
  Copy,
  Contact,
  FileText,
  Flag,
  Folder,
  FolderKanban,
  Folders,
  GanttChart,
  GitBranch,
  GraduationCap,
  Handshake,
  Headphones,
  KanbanSquare,
  Key,
  Landmark,
  LayoutDashboard,
  LineChart,
  List,
  Lock,
  Mail,
  Megaphone,
  MessageSquare,
  Package,
  Palette,
  Percent,
  PiggyBank,
  Receipt,
  RefreshCw,
  Settings2,
  Share2,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Split,
  StickyNote,
  Tag,
  Tags,
  Target,
  Ticket,
  Timer,
  TrendingUp,
  Upload,
  User,
  UserCheck,
  UserCog,
  Users,
  UsersRound,
  Video,
  Wallet,
  Warehouse,
  Webhook,
  Zap,
};

/**
 * Map of module icon filenames to Lucide icon names.
 * Modules store icon as filename (e.g., "pos.png", "hr.png") but we need Lucide icons for UI.
 */
const moduleIconAliases: Record<string, string> = {
  'pos.png': 'ShoppingCart',
  'hr.png': 'Briefcase',
  'crm.png': 'UsersRound',
  'events.png': 'Calendar',
  'cms.png': 'FileText',
  'social_media_marketing.png': 'Share2',
  'e_commerce.png': 'ShoppingBag',
  'live_agent.png': 'Headphones',
  'e_learning.png': 'GraduationCap',
};

export function resolveIcon(name: string | null | undefined, fallback: LucideIcon = LayoutDashboard): LucideIcon {
  if (!name) return fallback;
  // Check if it's a known module icon filename
  const aliasedName = moduleIconAliases[name] ?? name;
  // Remove .png extension if present for direct matches
  const cleanName = aliasedName.replace(/\.png$/, '');
  return iconMap[cleanName] ?? iconMap[aliasedName] ?? fallback;
}

export default iconMap;
