<?php

namespace Modules\Subscription\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Subscription\Entities\PlanFeature;
use Modules\Subscription\Entities\Plan;

class PlanFeatureSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $plans = Plan::all();

        if ($plans->isEmpty()) {
            $this->command->warn('No plans found. Skipping plan feature seeding.');
            return;
        }

        $planFeatures = [
            // Free Plan features
            [
                'plan_slug' => 'free-plan',
                'feature_key' => 'basic_dashboard',
                'name' => 'Basic Dashboard',
                'description' => 'Access to basic dashboard with essential features',
                'feature_type' => 'boolean',
                'feature_value' => 'true',
                'numeric_limit' => null,
                'is_unlimited' => false,
                'unit' => null,
                'sort_order' => 1,
                'is_highlighted' => false,
                'metadata' => null,
                'status' => 'active',
            ],
            [
                'plan_slug' => 'free-plan',
                'feature_key' => 'projects_limit',
                'name' => '5 Projects',
                'description' => 'Create up to 5 projects',
                'feature_type' => 'numeric',
                'feature_value' => null,
                'numeric_limit' => 5,
                'is_unlimited' => false,
                'unit' => 'projects',
                'sort_order' => 2,
                'is_highlighted' => true,
                'metadata' => null,
                'status' => 'active',
            ],
            [
                'plan_slug' => 'free-plan',
                'feature_key' => 'storage_limit',
                'name' => '1GB Storage',
                'description' => '1GB of file storage space',
                'feature_type' => 'numeric',
                'feature_value' => null,
                'numeric_limit' => 1,
                'is_unlimited' => false,
                'unit' => 'GB',
                'sort_order' => 3,
                'is_highlighted' => true,
                'metadata' => null,
                'status' => 'active',
            ],
            [
                'plan_slug' => 'free-plan',
                'feature_key' => 'email_support',
                'name' => 'Email Support',
                'description' => 'Email support with 48-hour response time',
                'feature_type' => 'boolean',
                'feature_value' => 'true',
                'numeric_limit' => null,
                'is_unlimited' => false,
                'unit' => null,
                'sort_order' => 4,
                'is_highlighted' => false,
                'metadata' => null,
                'status' => 'active',
            ],

            // Starter Plan features
            [
                'plan_slug' => 'starter-plan',
                'feature_key' => 'advanced_dashboard',
                'name' => 'Advanced Dashboard',
                'description' => 'Access to advanced dashboard with analytics',
                'feature_type' => 'boolean',
                'feature_value' => 'true',
                'numeric_limit' => null,
                'is_unlimited' => false,
                'unit' => null,
                'sort_order' => 1,
                'is_highlighted' => false,
                'metadata' => null,
                'status' => 'active',
            ],
            [
                'plan_slug' => 'starter-plan',
                'feature_key' => 'projects_limit',
                'name' => '25 Projects',
                'description' => 'Create up to 25 projects',
                'feature_type' => 'numeric',
                'feature_value' => null,
                'numeric_limit' => 25,
                'is_unlimited' => false,
                'unit' => 'projects',
                'sort_order' => 2,
                'is_highlighted' => true,
                'metadata' => null,
                'status' => 'active',
            ],
            [
                'plan_slug' => 'starter-plan',
                'feature_key' => 'storage_limit',
                'name' => '10GB Storage',
                'description' => '10GB of file storage space',
                'feature_type' => 'numeric',
                'feature_value' => null,
                'numeric_limit' => 10,
                'is_unlimited' => false,
                'unit' => 'GB',
                'sort_order' => 3,
                'is_highlighted' => true,
                'metadata' => null,
                'status' => 'active',
            ],
            [
                'plan_slug' => 'starter-plan',
                'feature_key' => 'priority_support',
                'name' => 'Priority Support',
                'description' => 'Priority email support with 24-hour response time',
                'feature_type' => 'boolean',
                'feature_value' => 'true',
                'numeric_limit' => null,
                'is_unlimited' => false,
                'unit' => null,
                'sort_order' => 4,
                'is_highlighted' => true,
                'metadata' => null,
                'status' => 'active',
            ],
            [
                'plan_slug' => 'starter-plan',
                'feature_key' => 'api_access',
                'name' => 'API Access',
                'description' => 'Basic API access for integrations',
                'feature_type' => 'boolean',
                'feature_value' => 'true',
                'numeric_limit' => null,
                'is_unlimited' => false,
                'unit' => null,
                'sort_order' => 5,
                'is_highlighted' => false,
                'metadata' => null,
                'status' => 'active',
            ],

            // Professional Plan features
            [
                'plan_slug' => 'professional-plan',
                'feature_key' => 'premium_dashboard',
                'name' => 'Premium Dashboard',
                'description' => 'Access to premium dashboard with advanced analytics',
                'feature_type' => 'boolean',
                'feature_value' => 'true',
                'numeric_limit' => null,
                'is_unlimited' => false,
                'unit' => null,
                'sort_order' => 1,
                'is_highlighted' => false,
                'metadata' => null,
                'status' => 'active',
            ],
            [
                'plan_slug' => 'professional-plan',
                'feature_key' => 'unlimited_projects',
                'name' => 'Unlimited Projects',
                'description' => 'Create unlimited projects',
                'feature_type' => 'numeric',
                'feature_value' => null,
                'numeric_limit' => null,
                'is_unlimited' => true,
                'unit' => 'projects',
                'sort_order' => 2,
                'is_highlighted' => true,
                'metadata' => null,
                'status' => 'active',
            ],
            [
                'plan_slug' => 'professional-plan',
                'feature_key' => 'storage_limit',
                'name' => '100GB Storage',
                'description' => '100GB of file storage space',
                'feature_type' => 'numeric',
                'feature_value' => null,
                'numeric_limit' => 100,
                'is_unlimited' => false,
                'unit' => 'GB',
                'sort_order' => 3,
                'is_highlighted' => true,
                'metadata' => null,
                'status' => 'active',
            ],
            [
                'plan_slug' => 'professional-plan',
                'feature_key' => 'live_chat_support',
                'name' => 'Live Chat Support',
                'description' => 'Live chat support with 12-hour response time',
                'feature_type' => 'boolean',
                'feature_value' => 'true',
                'numeric_limit' => null,
                'is_unlimited' => false,
                'unit' => null,
                'sort_order' => 4,
                'is_highlighted' => true,
                'metadata' => null,
                'status' => 'active',
            ],
            [
                'plan_slug' => 'professional-plan',
                'feature_key' => 'full_api_access',
                'name' => 'Full API Access',
                'description' => 'Full API access with rate limits',
                'feature_type' => 'boolean',
                'feature_value' => 'true',
                'numeric_limit' => null,
                'is_unlimited' => false,
                'unit' => null,
                'sort_order' => 5,
                'is_highlighted' => false,
                'metadata' => null,
                'status' => 'active',
            ],
            [
                'plan_slug' => 'professional-plan',
                'feature_key' => 'custom_integrations',
                'name' => 'Custom Integrations',
                'description' => 'Custom integrations and webhooks',
                'feature_type' => 'boolean',
                'feature_value' => 'true',
                'numeric_limit' => null,
                'is_unlimited' => false,
                'unit' => null,
                'sort_order' => 6,
                'is_highlighted' => false,
                'metadata' => null,
                'status' => 'active',
            ],
            [
                'plan_slug' => 'professional-plan',
                'feature_key' => 'advanced_analytics',
                'name' => 'Advanced Analytics',
                'description' => 'Advanced analytics and reporting features',
                'feature_type' => 'boolean',
                'feature_value' => 'true',
                'numeric_limit' => null,
                'is_unlimited' => false,
                'unit' => null,
                'sort_order' => 7,
                'is_highlighted' => false,
                'metadata' => null,
                'status' => 'active',
            ],

            // Enterprise Plan features
            [
                'plan_slug' => 'enterprise-plan',
                'feature_key' => 'custom_dashboard',
                'name' => 'Custom Dashboard',
                'description' => 'Fully customizable dashboard',
                'feature_type' => 'boolean',
                'feature_value' => 'true',
                'numeric_limit' => null,
                'is_unlimited' => false,
                'unit' => null,
                'sort_order' => 1,
                'is_highlighted' => false,
                'metadata' => null,
                'status' => 'active',
            ],
            [
                'plan_slug' => 'enterprise-plan',
                'feature_key' => 'unlimited_everything',
                'name' => 'Unlimited Everything',
                'description' => 'Unlimited projects, storage, and users',
                'feature_type' => 'numeric',
                'feature_value' => null,
                'numeric_limit' => null,
                'is_unlimited' => true,
                'unit' => null,
                'sort_order' => 2,
                'is_highlighted' => true,
                'metadata' => null,
                'status' => 'active',
            ],
            [
                'plan_slug' => 'enterprise-plan',
                'feature_key' => 'dedicated_support',
                'name' => 'Dedicated Support',
                'description' => 'Dedicated account manager and 24/7 support',
                'feature_type' => 'boolean',
                'feature_value' => 'true',
                'numeric_limit' => null,
                'is_unlimited' => false,
                'unit' => null,
                'sort_order' => 3,
                'is_highlighted' => true,
                'metadata' => null,
                'status' => 'active',
            ],
            [
                'plan_slug' => 'enterprise-plan',
                'feature_key' => 'unlimited_api',
                'name' => 'Unlimited API Access',
                'description' => 'Unlimited API access with no rate limits',
                'feature_type' => 'boolean',
                'feature_value' => 'true',
                'numeric_limit' => null,
                'is_unlimited' => false,
                'unit' => null,
                'sort_order' => 4,
                'is_highlighted' => false,
                'metadata' => null,
                'status' => 'active',
            ],
            [
                'plan_slug' => 'enterprise-plan',
                'feature_key' => 'custom_development',
                'name' => 'Custom Development',
                'description' => 'Custom development and integrations',
                'feature_type' => 'boolean',
                'feature_value' => 'true',
                'numeric_limit' => null,
                'is_unlimited' => false,
                'unit' => null,
                'sort_order' => 5,
                'is_highlighted' => false,
                'metadata' => null,
                'status' => 'active',
            ],
            [
                'plan_slug' => 'enterprise-plan',
                'feature_key' => 'sla_guarantee',
                'name' => 'SLA Guarantee',
                'description' => '99.9% uptime SLA guarantee',
                'feature_type' => 'boolean',
                'feature_value' => 'true',
                'numeric_limit' => null,
                'is_unlimited' => false,
                'unit' => null,
                'sort_order' => 6,
                'is_highlighted' => true,
                'metadata' => null,
                'status' => 'active',
            ],
            [
                'plan_slug' => 'enterprise-plan',
                'feature_key' => 'on_premise',
                'name' => 'On-premise Option',
                'description' => 'On-premise deployment option',
                'feature_type' => 'boolean',
                'feature_value' => 'true',
                'numeric_limit' => null,
                'is_unlimited' => false,
                'unit' => null,
                'sort_order' => 7,
                'is_highlighted' => false,
                'metadata' => null,
                'status' => 'active',
            ],
        ];

        foreach ($planFeatures as $featureData) {
            $plan = $plans->where('slug', $featureData['plan_slug'])->first();
            if ($plan) {
                unset($featureData['plan_slug']);
                $featureData['plan_id'] = $plan->id;
                PlanFeature::create($featureData);
            }
        }

        $this->command->info('Plan features seeded successfully!');
    }
}
